# Generated by Django 4.1.5 on 2023-01-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDiscipline', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTeam', models.CharField(default='teamExt', max_length=10)),
                ('fullnameTeam', models.CharField(max_length=100)),
                ('colorteam', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgliveapp.discipline')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgliveapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Matche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateMatche', models.DateTimeField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgliveapp.discipline')),
            ],
        ),
    ]
