# Generated by Django 4.1.5 on 2023-03-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgliveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamranking',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsmatch',
            name='decidedBy',
            field=models.CharField(choices=[('n', 'normal'), ('p', 'penalty or other'), ('f', ' team forfeit')], default='n', max_length=2),
        ),
    ]
