# Generated by Django 4.1.5 on 2023-02-13 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgliveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleticsmatch',
            name='athleticsMatchDesc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='athleticsmatch',
            name='dateMatch',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleticsparticipation',
            name='athleticsDesc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='collectivematch',
            name='collectiveMatchDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='collectivematch',
            name='collectiveMatchDesc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='collectivematch',
            name='sexe',
            field=models.CharField(blank=True, default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='collectivematch',
            name='stage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='collectivematch',
            name='timeLenght',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='detailsmatch',
            name='decidedBy',
            field=models.CharField(choices=[('n', 'normal'), ('p', 'penalty or other')], default='n', max_length=2),
        ),
        migrations.AlterField(
            model_name='detailsmatch',
            name='win_lose',
            field=models.CharField(blank=True, choices=[('w', 'won'), ('l', 'lost')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerAge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='descriptionTeam',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='globalRank',
            field=models.IntegerField(blank=True),
        ),
    ]
