# Generated by Django 4.1.5 on 2023-03-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgliveapp', '0002_teamranking_points_alter_detailsmatch_decidedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='totalPoints',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
