# Generated by Django 4.1.5 on 2023-02-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esgliveapp', '0003_alter_collectivematch_collectivematchdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=40)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgliveapp.team')),
            ],
        ),
    ]
