# Generated by Django 4.1.5 on 2023-03-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgliveapp', '0003_team_totalpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamranking',
            name='sexe',
            field=models.CharField(choices=[('m', 'man'), ('f', 'woman')], default='m', max_length=2),
        ),
    ]
