# Generated by Django 4.1.5 on 2023-03-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esgliveapp', '0004_alter_teamranking_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectivematch',
            name='collectiveMatchDesc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collectivematch',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectivematch',
            name='timeLenght',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsmatch',
            name='captainId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esgliveapp.player'),
        ),
    ]
