# Generated by Django 4.1.5 on 2023-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgliveapp', '0004_teamranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamranking',
            name='matchPlayed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
